name: Run packer build on a template file

on:
  push:
    branches:
        - main
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - name: print console log
        run: echo 'started packer build yml'
      - uses: actions/checkout@v1
      - name: Packer build
        if: github.repositry == 'packer-validation'
        uses: hashicorp/setup-packer@v2
        with:
          templateFile: 'aws-ubuntu.pkr.hcl'
          workingDir: ${{ github.workspace }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      - name: Run Packer build
        run: packer build aws-ubuntu.pkr.hcl